directory: ../mnt/library/
library: ../state/beets/musiclibrary.db

pluginpath:
  - beetsplug

plugins:
  - chroma
  - fish
  - edit
  - badfiles
  - fetchart
  - embedart
  - mbsync
  - musicbrainz
  - duplicates
  - chroma
  - convert
  - scrub
  - audit
  - genre
  - replaygain
  - info
  - edit
  - albumtypes

albumtypes:
  types:
    - ep: 'EP'
    - single: 'Single'
    - soundtrack: 'OST'
    - live: 'Live'
    - compilation: 'Anthology'
    - remix: 'Remix'
  ignore_va: compilation
  bracket: '[]'


musicbrainz:
  host: musicbrainz.org
  https: no
  genres: no
  external_ids:
    discogs: yes
    spotify: yes
    bandcamp: yes

import:
  move: yes
  copy: no
  write: yes
  resume: ask
  incremental: yes
  incremental_skip_later: yes
  quiet_fallback: skip
  log: ../state/beets/import.log
  from_scratch: no
  duplicate_action: ask
  timid: no

paths:
  default: $albumartist/[$year]$atypes $album%aunique{}/$track - $title
  singleton: Non-Album/$artist/$title
  comp: Compilations/$album%aunique{ [$year]}/$track - $title

discogs:
  user_token: ewHIvXlRXcouGPGQzTPLexzmtatTPPFRIrShPHnm

fetchart:
  auto: yes
  cautious: yes
  maxwidth: 1200
  cover_names: cover folder front art album
  sources:
    - filesystem
    - coverart
    - itunes
    - amazon

embedart:
  auto: yes
  ifempty: yes
  remove_art_file: no

chroma:
  auto: yes

match:
  preferred:
    countries: [US, GB, JP]
    media: [Digital Media, CD, 12" Vinyl, Vinyl]

lastgenre:
  auto: yes
  source: album
  count: 3
  min_weight: 50
  force: yes
  keep_existing: yes
  whitelist: no
  ignorelist:
    '*':
      - '(?i)^seen live$'
      - '(?i)^\\d{4}(?:\\s+(?:albums?|releases?))?$'
      - '(?i)^\\d{2}(?:\\d{2})?s$'
      - '(?i)^top .+ albums? of the decade.*$'
      - '(?i)^(?:albums?|releases?)$'
      - '(?i)^new (?:album|release)$'
      - '(?i)^(?:favorite|favourite)(?: live)? albums?$'
      - '(?i)^(?:favorite|favourite) (?:songs|tracks)$'
      - '(?i)^favo(?:u)?rites?$'
      - '(?i)^my favo(?:u)?rite(?:s)?$'
      - '(?i)^under \\d+ listeners$'
      - '(?i)^albums i own$'
      - '(?i)^free download$'
      - '(?i)^scrobbles to edit$'
      - '(?i)^check out$'
      - '(?i)^(?:owned|vinyl|youtube|test)$'
      - '(?i)^(?:amazing|awesome|cool|catchy|hype|masterpiece|playful|raw|sexy|summer)$'
      - '(?i)^beautiful (?:voice|vocals)$'
      - '(?i)^(?:female|male) vocalists?$'
      - '(?i)^(?:american|british|canadian|hungarian|irish|japanese)$'
      - '(?i)^(?:another questionmark|dogs and cats|food and drink|parts of the body|randomvalue)$'



convert:
  auto: yes
  auto_keep: no
  delete_originals: yes
  never_convert_lossy_files: yes
  tmpdir: /home/mandos/dev/music-cleanup/mnt/uploads/tmp
  format: flac
  formats:
    flac:
      command: ffmpeg -i $source -y -vn -c:a flac $dest
      extension: flac

acoustid:
  apikey: Zi3a4lgPD4

replaygain:
  backend: ffmpeg
  overwrite: no

replace:
  '[\\/]': _
  '^\\.': _
